---
- name: Ensuring Docker Nginx image is present
  docker_image:
    name: nginx
    tag: 1.15.5
    pull: yes

- name: Ensuring /etc/nginx is present
  file:
    path: /etc/nginx
    state: directory
    mode: 0755

- name: Ensuring /etc/nginx/conf.d is present
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: Ensuring /etc/nginx/nginx.conf exists
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Ensuring Docker Nginx container is running
  docker_container:
    name: proxy
    image: nginx
    state: started
    recreate: yes
    restart_policy: always
    network_mode: bridge
    published_ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /etc/nginx:/etc/nginx
